// src/theme/theme.ts
// ─── SINGLE SOURCE OF TRUTH ───────────────────────────────────────────────────
// Every color, spacing, radius, and typography value in the app comes from here.
// To retheme the entire app, edit only this file.

const palette = {
  red: "#E60023",
  redDark: "#B60000",
  redLight: "#FF3352",
  white: "#FFFFFF",
  black: "#000000",
  // Neutrals — light mode
  gray50: "#F9F9F9",
  gray100: "#F1F1F1",
  gray200: "#E1E1E1",
  gray300: "#C9C9C9",
  gray400: "#A8A8A8",
  gray500: "#767676",
  gray600: "#555555",
  gray700: "#333333",
  gray800: "#1A1A1A",
  gray900: "#111111",
  // Accent
  overlay: "rgba(0,0,0,0.45)",
  overlayLight: "rgba(0,0,0,0.12)",
};

export const theme = {
  colors: {
    light: {
      background: palette.white,
      surface: palette.gray50,
      surfaceElevated: palette.white,
      card: palette.white,
      primary: palette.red,
      primaryDark: palette.redDark,
      primaryLight: palette.redLight,
      text: palette.gray900,
      textSecondary: palette.gray500,
      textTertiary: palette.gray400,
      textInverted: palette.white,
      border: palette.gray200,
      borderStrong: palette.gray300,
      placeholder: palette.gray300,
      icon: palette.gray700,
      iconMuted: palette.gray400,
      overlay: palette.overlay,
      overlayLight: palette.overlayLight,
      success: "#00A854",
      error: "#D93025",
      warning: "#F5A623",
      tabBar: palette.white,
      tabBarBorder: palette.gray200,
      tabBarActive: palette.red,
      tabBarInactive: palette.gray400,
      sidebarBg: palette.white,
      sidebarBorder: palette.gray200,
      inputBg: palette.gray100,
      inputBorder: palette.gray200,
      inputBorderFocused: palette.red,
      skeleton: palette.gray200,
      skeletonShimmer: palette.gray100,
      pillBg: palette.gray100,
      pillBgActive: palette.red,
      pillText: palette.gray700,
      pillTextActive: palette.white,
      badgeBg: palette.red,
      badgeText: palette.white,
    },
    dark: {
      background: palette.gray900,
      surface: palette.gray800,
      surfaceElevated: "#222222",
      card: "#1E1E1E",
      primary: palette.red,
      primaryDark: palette.redDark,
      primaryLight: palette.redLight,
      text: "#F0F0F0",
      textSecondary: palette.gray400,
      textTertiary: palette.gray500,
      textInverted: palette.gray900,
      border: "#2A2A2A",
      borderStrong: "#3A3A3A",
      placeholder: "#3A3A3A",
      icon: "#E0E0E0",
      iconMuted: palette.gray500,
      overlay: palette.overlay,
      overlayLight: "rgba(255,255,255,0.08)",
      success: "#00C96B",
      error: "#FF6B6B",
      warning: "#FFB347",
      tabBar: "#111111",
      tabBarBorder: "#222222",
      tabBarActive: palette.red,
      tabBarInactive: palette.gray500,
      sidebarBg: "#111111",
      sidebarBorder: "#222222",
      inputBg: "#1E1E1E",
      inputBorder: "#2A2A2A",
      inputBorderFocused: palette.red,
      skeleton: "#2A2A2A",
      skeletonShimmer: "#333333",
      pillBg: "#2A2A2A",
      pillBgActive: palette.red,
      pillText: "#CCCCCC",
      pillTextActive: palette.white,
      badgeBg: palette.red,
      badgeText: palette.white,
    },
  },

  spacing: {
    xxs: 2,
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
    xxxl: 64,
  },

  radius: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    pill: 999,
  },

  typography: {
    families: {
      heading: "Poppins_600SemiBold",
      headingBold: "Poppins_700Bold",
      headingMedium: "Poppins_500Medium",
      body: "DMSans_400Regular",
      bodyMedium: "DMSans_500Medium",
      bodyBold: "DMSans_700Bold",
    },
    scale: {
      display: 36,
      h1: 28,
      h2: 22,
      h3: 18,
      bodyLarge: 16,
      body: 14,
      bodySmall: 13,
      caption: 12,
      tiny: 10,
    },
    lineHeight: {
      display: 44,
      h1: 36,
      h2: 30,
      h3: 26,
      bodyLarge: 24,
      body: 22,
      bodySmall: 20,
      caption: 18,
      tiny: 16,
    },
    weights: {
      regular: "400" as const,
      medium: "500" as const,
      semibold: "600" as const,
      bold: "700" as const,
    },
  },

  shadows: {
    sm: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.08,
      shadowRadius: 4,
      elevation: 2,
    },
    md: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.12,
      shadowRadius: 8,
      elevation: 4,
    },
    lg: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.18,
      shadowRadius: 16,
      elevation: 8,
    },
  },

  breakpoints: {
    sm: 480,
    md: 768,
    lg: 1024,
    xl: 1280,
  },

  grid: {
    gap: 8,
    // columns by breakpoint
    cols: {
      sm: 2,
      md: 3,
      lg: 4,
      xl: 5,
    },
    maxWidth: 1400,
    sidebarWidth: 240,
    contentPadding: 16,
  },
} as const;

export type ColorScheme = "light" | "dark";
export type ThemeColors = Record<keyof typeof theme.colors.light, string>;
export type Theme = typeof theme;
